# Generated by Django 4.2.8 on 2023-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("cooking_time", models.PositiveIntegerField(help_text="in minutes")),
                ("ingredients", models.CharField(max_length=300)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("intermediate", "Intermediate"),
                            ("hard", "Hard"),
                        ],
                        max_length=12,
                    ),
                ),
            ],
        ),
    ]
