# Generated by Django 4.2.8 on 2023-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="customers"),
        ),
    ]
